/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public\models\TransistorAnimationAccurate.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const AnimationOfTransistor = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/TransistorAnimationAccurate.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
    actions[names[1]].reset().fadeIn(0.5).play()
    actions[names[2]].reset().fadeIn(0.5).play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera" position={[-0.32, 12.818, 21.166]} rotation={[1.179, 0, 0]} />
        <group name="Armature" position={[-0.026, -0.326, -1.662]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.002']} skeleton={nodes.Cube002.skeleton} />
          <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.002']} skeleton={nodes.Cube003.skeleton} />
          <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.002']} skeleton={nodes.Cube004.skeleton} />
        </group>
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Material} position={[-0.451, 6.143, -1.744]} rotation={[0.002, 0.075, -2.942]} scale={0.13} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[0.002, 6.733, -1.742]} rotation={[-0.85, 0.211, 0.173]} scale={0.13} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.004']} position={[3.268, 0.498, -1.667]} rotation={[-0.051, -0.709, 1.468]} scale={0.13} />
      </group>
    </group>
  )
}

export default AnimationOfTransistor

useGLTF.preload('./models/TransistorAnimationAccurate.glb')
