
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Transistor(props) {
  const { nodes, materials } = useGLTF("./models/TransistorModelsTwo.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 5.53, 0]} scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/TransistorModelsTwo.glb");


